config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resources :questions do
    put :hide, on: :member
  end

  resource :session, only: %i[new create destroy]
  resources :users, param: :nickname, expect: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  validates :body, presence: true, length: { maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :delete_all
  has_many :authored_questions, class_name: 'Question', foreign_key: 'author_id', dependent: :nullify

  has_secure_password

  before_validation :downcase_nickname

  validates :header_color, presence: true, format: { with: /\A#\h{3}{1,2}\z/ }
  validates :email, presence: true, uniqueness: true,
    format: { with: /([a-z0-9_\.-]+)@([a-z0-9_\.-]+)\.([a-z\.]{2,6})/ }
  validates :nickname, presence: true, uniqueness: true,
    format: { with: /[a-z0-9_]/ }, length: { maximum: 40 }

  include Gravtastic
  gravtastic(secure: true, filetype: :png, size: 100, default: 'retro')

  def downcase_nickname
    nickname&.downcase!
  end

  def to_param
    nickname
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update destroy edit hide]
  before_action :set_question_for_current_user, only: %i[update destroy edit hide]

  def create
    question_params = params.require(:question).permit(:body, :user_id)
    @question = Question.new(question_params)
    @question.author = current_user

    if  @question.save
      redirect_to user_path(@question.user), notice: "Новый вопрос создан"
    else
      flash.now[:alert] = "При попытке создать вопрос вознилки ошибки!"
      render :new
    end
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)
    @question.update(question_params)

    redirect_to user_path(@question.user), notice: "Изменения сохранены"
  end

  def destroy
    @user = @question.user
    @question.destroy

    redirect_to user_path(@user), notice: "Вопрос удален"
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.order(created_at: :desc).last(10)
    @users = User.order(created_at: :desc).last(10)
  end

  def new
    @user = User.find_by(nickname: params[:nickname])
    @question = Question.new(user: @user)
  end

  def edit
  end

  def hide
    @question.update(hidden: true)

    redirect_to questions_path
  end

  private

  def create_question_params
    params.require(:question).permit(:body, :user_id)
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user_params = params.require(:session)
    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id

      redirect_to root_path, notice: "Вы вошли на сайт"
    else
      flash.now[:alert] = "Неправильный email или пароль"

      render :new
    end
  end

  def destroy
  session.delete(:user_id)

  redirect_to root_path, notice: "Вы вышли из аккаунта"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      redirect_to root_path, notice: 'Вы успешно зарегистрировались!'
    else
      flash.now[:alert] = 'Не верно заполнены поля регистрации'

      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)

      redirect_to root_path, notice: 'Данные пользователя обновлены'
    else
      flash.now[:alert] = 'Возникла ошибка при попытке сохранения'

      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'Пользователь удален'
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @question = Question.new(user: @user)
  end

  private

  def user_params
  params.require(:user).permit(
        :name, :nickname, :email, :header_color, :password, :password_confirmation
  )
  end

  def set_user
    @user = User.find_by(nickname: params[:nickname])
  end

  def authorize_user
    redirect_with_alert unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end

  def current_user_header_color
    current_user&.header_color || "#370617"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def author_present(author)
    if author == current_user && current_user.present?
      "мой вопрос"
    elsif author.present?
      link_to "вопрос от #{display_nickname(author)}", user_path(author)
    else
      "вопрос от анонима"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def display_nickname(user)
    "@#{user.nickname}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Askme</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
        <%elsif flash[:alert].present?%>
        <p class="mb mt message message-alert"><%= flash[:alert] %></p>
      <% end %>
    </div>

    <div class="wrapper">
      <%= content_tag "div", class: "navbar", style: "background-color: #{current_user_header_color}" do %>
      <p class="title-sm text-bold"><%= link_to "AskMe!", root_path%></p>
        <div>
          <% if current_user.present?%>
          <%= link_to display_nickname(current_user), user_path(current_user), class: "mr-sm"%>
          <%= button_to "Выйти", session_path, method: :delete%>
          <% else%>
          <%= link_to "Регистрация", new_user_path, class: "button button-yellow mr-sm" %>
          <%= link_to "Вход", new_session_path, class: "button button-yellow" %>
          <% end %>
        </div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: question, data: {turbo: false} do |form| %>
  <%= form.hidden_field :user_id %>
  <p><%= form.label :body, 'текст вопроса' %></p>
  <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

  <% if question.persisted?%>
    <p class="mt"><%= form.label :answer, 'Oтвет' %></p>
    <p><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
  <%end%>

  <p class="mt"><%= form.submit 'сохранить', class: 'button button-main'%></p>
  <p class="mt"><%= link_to 'Вернуться', :back%></p>
<%end%>

app/views/questions/_question.html.erb
<% hidden_klass = question.hidden ? "question-hidden" : "question-visible" %>
  <%= content_tag :div, class: ["mb-sm", hidden_klass] do %>
  <%= simple_format h(question.body) %>
<% end %>

<% if question.answer.present? %>
  <div class="mb-sm text-dark-red">
    <p><%= question.answer %></p>
  </div>
<% end %>

<p class="text-sm text-gray">
  <%= author_present(question.author) %>
</p>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(question.created_at, format: :short) %>
  </div>

  <% if current_user == question.user %>
    <div>
      <% edit_icon = (question.answer.present?) ? 'pencil' : 'reply' %>
      <%= link_to fa_icon(edit_icon), edit_question_path(question), title: 'Изменить вопрос', class:  'mr-sm' %>
      <%= button_to fa_icon('trash-o'), question_path(question), method: :delete, title: 'Удалить вопрос' %>

      <% unless question.hidden %>
        <%= button_to fa_icon('eye-slash'), hide_question_path(question), method: :put, title: 'Скрыть вопрос'%>
      <% end %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="wrapper">
  <div class="container">
    <h2 class="title-lg mb">Редактирование вопроса <%= @question.id%></h2>

      <%= render 'form', question: @question %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="wrapper">
  <div class="container">
    <h2 class="title-lg mb">
      Недавно добавились
    </h2>

    <div class="users-box">
      <% @users.each do |user| %>
        <%= render partial: 'users/user_avatar', locals: {user: user} %>
      <% end %>
    </div>
  </div>
  <div class="container mt">
    <h2 class="title-lg">
      <%= inclination(@questions.count, 'Последний', 'Последние', 'Последние') %>
      <%= @questions.count %>
      <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
    </h2>
  </div>
  <% @questions.each do |question| %>
    <div class="mt-sm container">
      <p class="mb text-sm text-grey">
        Вопрос <%= link_to "##{question.id}", question_path(question) %>
        для юзера <%= link_to display_nickname(question.user), user_path(question.user) %>
      </p>
      <%= render partial: 'question', object: question %>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="wrapper">
  <div class="container">
    <h2 class="title-lg ">Новый вопрос</h2>

    <% @question.errors.full_messages.each do |message| %>
      <p class="mb-sm text-red"><%= message %></p>
    <% end %>
    <p class="mb">для <%= link_to @user[:nickname], user_path(@question.user) %></p>
    <%= render 'form', question: @question %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="wrapper">
<div class="container">
    <h2 class="title-lg mb">Вопрос <%= @question.id %></h2>
    <p class="mt-sm"><%= link_to "Все вопросы @#{@question.user.nickname}", user_path(@question.user) %></p>

    <p class="mt"><%= link_to "Все вопросы", questions_path %></p>
  </div>
  <div class="mt-sm container">
    <%= render 'question', question: @question %>
  </div>
</div>

app/views/users/_no_questions.html.erb
<div class="container text-center">
  <p class="title-sm text-grey">
    У этого пользователя пока никто ничего не спросил
  </p>

  <div class="mt-lg mb-lg fa-4x text-light-grey">
    <%= fa_stacked_icon 'question', base: 'circle-o' %>
  </div>

  <%= link_to "Задать вопрос", new_question_path(nickname: user),
    class: 'button button-main' %>
</div>

app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg#{user.id % 5}" %>

<div class="users-box-user <%= background_class %> rounded">
  <a href="<%= user_path(user) %>">
    <%= image_tag user.gravatar_url, title: "@#{user.nickname}", class: 'rounded' %>
  </a>
</div>

app/views/users/edit.html.erb
<div class="wrapper">
  <div class="container">
    <h2 class="title">Редактирование профиля</h2>

    <% if @user.errors.any? %>
      <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
       <p class="mb-sm text-red"><%= message %></p>
      <% end %>
      </div>
    <% end %>

    <div class="mt">
      <p><%= image_tag @user.gravatar_url, title: "@#{@user.nickname}", class: 'rounded' %></p>
      <p class="text-sm">Чтобы добавить или поменять аватар — зарегистрируйтесь на <%= link_to "Gravatar", 'https://gravatar.com' %> и загрузите фото</p>
    </div>

    <div class="mt">
      <%= form_with model: @user, data: {turbo: false} do |form| %>
        <p><%= form.label :name, 'Имя' %></p>
        <p><%= form.text_field :name, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :header_color, 'Цвет шапки сайта' %></p>
        <p><%= form.color_field :header_color, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
        <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

        <p class="mt-lg text-sm">Если не хотите менять пароль — оставьте эти поля пустыми!</p>

        <p class="mt"><%= form.label :password, 'Пароль' %></p>
        <p><%= form.password_field :password, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :password_confirmation, 'Подтверждение пароля' %></p>
        <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

        <p class="mt-lg">
        <%= form.submit "Сохранить", class: 'button button-main' %>
        <span class="text-sm">или <%= link_to "вернуться", :back %></span>
        </p>
      <% end %>
    </div>
    <div class="mt-lg">
    <%= button_to "Удалить профиль", user_path(@user),
      method: :delete,
      form: {data: {turbo_confirm: "Вы точно хотите удалить свой профиль?"}},
      class: 'text-red text-sm' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="wrapper">
  <div class="container">
    <h2 class="title">Присоединяйся и спрашивай</h2>
  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>
    <div class="mt">
      <%= form_with model: @user, data: {turbo: false} do |form|%>
        <p><%= form.label :name, 'Ваше имя' %></p>
        <p><%= form.text_field :name, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
        <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :email %></p>
        <p><%= form.text_field :email, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :password %></p>
        <p><%= form.password_field :password, class: 'form-text-field' %></p>

                <p class="mt"><%= form.label :password_confirmation %></p>
        <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

        <p><%= form.submit "Зарегистрироваться", class: 'button button-main mt-lg' %></p>
      <%end%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <% if @questions.any? %>
    <div class="container">
      <div class="user-box">
        <h2 class="title-lg mt-lg"><%= @user.name%></h2>

        <div class="mt">
          <%= render partial: 'users/user_avatar', locals: {user: @user} %>
        </div>

       <% if current_user == @user %>
          <p class="mt mb-lg">
            <%= link_to fa_icon('pencil'), edit_user_path(@user) %>
          </p>
        <% end %>

        <p class="text-bold mt mb-lg"><%= display_nickname(@user)%></p>
      </div>
      <div class="container">
        <%= link_to "Cпроси меня", new_question_path(nickname: @user), class: "button button-yellow"%>
      </div>

      <p class="mt">
        <%= render 'questions/form', question: @question %>
      </p>
    </div>

    <div class="container mt-sm">
      <h2 class="title-lg">
        <%= @questions.count %>
        <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
      </h2>
    </div>

    <% @questions.each do |question| %>
      <div class="mt-sm container">
        <%= render question %>
      </div>
    <% end %>
  <% else %>
    <%= render partial: 'no_questions', locals: {user: @user} %>
  <%end%>
</div>